/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;
import java.util.Optional;
import javax.swing.JOptionPane;
import model.EmpProfile;
import model.EmpList;
/**
 *
 * @author anamikabharali
 */

public class UpdateJPanel extends javax.swing.JPanel {
    /**
     * Creates new form UpdateJPanel
     */

    EmpList history;
    public UpdateJPanel(EmpList history, String updateid) {
        initComponents();
        this.updateid=updateid;
        this.history = history;
        boolean found = false;
        for(EmpProfile emp : history.getList()){
            if (emp.getempid()==Integer.parseInt(updateid)){
                txtage.setText(String.valueOf(emp.getage()));
                txtdepartment.setText(emp.getdepartment());
                txtemailid.setText(emp.getemail());
                txtempid.setText(String.valueOf(emp.getempid()));
                txtgender.setText(emp.getgender());
                txtlevel.setText(String.valueOf(emp.getlevel()));
                txtname.setText(emp.getname());
                txtphone.setText(emp.getcontactno());
                txtposition.setText(emp.getposition());
                txtstartdate.setText(emp.getstartdate());
                found=true;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbphone = new javax.swing.JLabel();
        txtemailid = new javax.swing.JTextField();
        lbemail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbphoto = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        lbempid = new javax.swing.JLabel();
        txtempid = new javax.swing.JTextField();
        btnupdate = new javax.swing.JButton();
        lbage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtgender = new javax.swing.JTextField();
        lbgender = new javax.swing.JLabel();
        txtstartdate = new javax.swing.JTextField();
        lbstartdate = new javax.swing.JLabel();
        txtlevel = new javax.swing.JTextField();
        lblevel = new javax.swing.JLabel();
        txtdepartment = new javax.swing.JTextField();
        lbdepartment = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        lbposition = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();

        lbphone.setText("Phone no");

        lbemail.setText("Email ID");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Update Employee Record");

        lbphoto.setText("Profile Photo");

        lbname.setText("Name");

        lbempid.setText("Employee ID");

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        lbage.setText("Age");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        lbgender.setText("Gender");

        txtstartdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstartdateActionPerformed(evt);
            }
        });

        lbstartdate.setText("Start Date");

        txtlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlevelActionPerformed(evt);
            }
        });

        lblevel.setText("Level");

        lbdepartment.setText("Department");

        lbposition.setText("Position");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbphoto)
                    .addComponent(lbemail)
                    .addComponent(lbphone)
                    .addComponent(lbdepartment)
                    .addComponent(lbposition)
                    .addComponent(lbempid)
                    .addComponent(lbname)
                    .addComponent(lbstartdate)
                    .addComponent(lblevel)
                    .addComponent(lbage)
                    .addComponent(lbgender))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtname)
                        .addComponent(txtempid)
                        .addComponent(txtstartdate)
                        .addComponent(txtlevel)
                        .addComponent(txtdepartment)
                        .addComponent(txtposition)
                        .addComponent(txtphone, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                        .addComponent(txtemailid))
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnupdate)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(lbname))
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbempid)
                    .addComponent(txtempid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbage)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbgender)
                    .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbstartdate)
                    .addComponent(txtstartdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblevel)
                    .addComponent(txtlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbdepartment)
                    .addComponent(txtdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbposition)
                    .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbphone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbemail)
                    .addComponent(txtemailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbphoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnupdate)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        
        
        Optional<EmpProfile> empp=history.getList().stream().filter(A->A.getempid()==Integer.parseInt(updateid)).findFirst();
        if (empp.isPresent()){
            EmpProfile emp=empp.get();
        emp.setname(txtname.getText());
        emp.setempid(Integer.parseInt(txtempid.getText()));
        emp.setage(Integer.parseInt(txtage.getText()));
        emp.setgender(txtgender.getText());
        emp.setstartdate(txtstartdate.getText());
        emp.setlevel(Integer.parseInt(txtlevel.getText()));
        emp.setdepartment(txtdepartment.getText());
        emp.setposition(txtposition.getText());
        emp.setemail(txtemailid.getText());
        emp.setcontactno(txtphone.getText());
        JOptionPane.showMessageDialog(this, "Employee Profile updated");}
        else
            JOptionPane.showMessageDialog(this, "Employee Profile not found");
            

        txtage.setText("");
        txtdepartment.setText("");
        txtemailid.setText("");
        txtempid.setText("");
        txtgender.setText("");
        txtlevel.setText("");
        txtname.setText("");
        txtphone.setText("");
        txtposition.setText("");
        txtstartdate.setText("");

    }//GEN-LAST:event_btnupdateActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtstartdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstartdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstartdateActionPerformed

    private void txtlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlevelActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtlevelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbage;
    private javax.swing.JLabel lbdepartment;
    private javax.swing.JLabel lbemail;
    private javax.swing.JLabel lbempid;
    private javax.swing.JLabel lbgender;
    private javax.swing.JLabel lblevel;
    private javax.swing.JLabel lbname;
    private javax.swing.JLabel lbphone;
    private javax.swing.JLabel lbphoto;
    private javax.swing.JLabel lbposition;
    private javax.swing.JLabel lbstartdate;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdepartment;
    private javax.swing.JTextField txtemailid;
    private javax.swing.JTextField txtempid;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlevel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtstartdate;
    // End of variables declaration//GEN-END:variables
    private String updateid;
}
