/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UIUX;

/**
 *
 * @author anamikabharali
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    public DoctorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Doctorlabelrec = new javax.swing.JLabel();
        Doctorlabelview = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        doctortable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        doctorsearchtxt = new javax.swing.JTextField();
        doctorsearchbtn = new javax.swing.JButton();
        doctornamelabel = new javax.swing.JLabel();
        doctornametxt = new javax.swing.JTextField();
        doctorpphnotxt = new javax.swing.JTextField();
        doctorpphnolabel = new javax.swing.JLabel();
        doctordatetxt = new javax.swing.JTextField();
        doctordatelabel = new javax.swing.JLabel();
        doctortemptxt = new javax.swing.JTextField();
        doctortemplabel = new javax.swing.JLabel();
        doctorbptxt = new javax.swing.JTextField();
        doctorbplabel = new javax.swing.JLabel();
        doctorpulsetxt = new javax.swing.JTextField();
        doctorpulselabel = new javax.swing.JLabel();
        doctordiagnosistxt = new javax.swing.JTextField();
        doctordiagnosislabel = new javax.swing.JLabel();
        doctorrecordbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        Doctorlabelrec.setBackground(new java.awt.Color(255, 255, 255));
        Doctorlabelrec.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        Doctorlabelrec.setForeground(new java.awt.Color(0, 153, 255));
        Doctorlabelrec.setText("Record an Encounter");

        Doctorlabelview.setBackground(new java.awt.Color(255, 255, 255));
        Doctorlabelview.setFont(new java.awt.Font("Tamil MN", 1, 14)); // NOI18N
        Doctorlabelview.setForeground(new java.awt.Color(0, 153, 255));
        Doctorlabelview.setText("View Previous Encounters");

        doctortable.setFont(new java.awt.Font("Tamil MN", 0, 13)); // NOI18N
        doctortable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DATE", "DOCTOR", "TEMPERATURE", "BP", "PULSE", "DIAGNOSIS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(doctortable);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        jLabel1.setText("Patient's Phone Number");

        doctorsearchtxt.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctorsearchtxt.setForeground(new java.awt.Color(204, 204, 204));
        doctorsearchtxt.setText("XXXXXXXXXX");

        doctorsearchbtn.setBackground(new java.awt.Color(0, 153, 255));
        doctorsearchbtn.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctorsearchbtn.setForeground(new java.awt.Color(255, 255, 255));
        doctorsearchbtn.setText("Search");
        doctorsearchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorsearchbtnActionPerformed(evt);
            }
        });

        doctornamelabel.setBackground(new java.awt.Color(255, 255, 255));
        doctornamelabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctornamelabel.setText("Doctor Name");

        doctorpphnolabel.setBackground(new java.awt.Color(255, 255, 255));
        doctorpphnolabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctorpphnolabel.setText("Patient Phone No");

        doctordatelabel.setBackground(new java.awt.Color(255, 255, 255));
        doctordatelabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctordatelabel.setText("Date");

        doctortemplabel.setBackground(new java.awt.Color(255, 255, 255));
        doctortemplabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctortemplabel.setText("Tempurature");

        doctorbplabel.setBackground(new java.awt.Color(255, 255, 255));
        doctorbplabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctorbplabel.setText("Blood Pressure");

        doctorpulselabel.setBackground(new java.awt.Color(255, 255, 255));
        doctorpulselabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctorpulselabel.setText("Pulse");

        doctordiagnosislabel.setBackground(new java.awt.Color(255, 255, 255));
        doctordiagnosislabel.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctordiagnosislabel.setText("Diagnosis");

        doctorrecordbtn.setBackground(new java.awt.Color(0, 153, 255));
        doctorrecordbtn.setFont(new java.awt.Font("Tamil MN", 0, 14)); // NOI18N
        doctorrecordbtn.setForeground(new java.awt.Color(255, 255, 255));
        doctorrecordbtn.setText("Record");

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/anamikabharali/Desktop/Screen Shot 2022-10-28 at 12.17.44 AM.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Doctorlabelview)
                .addGap(446, 446, 446))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doctorbplabel)
                                    .addComponent(doctorpulselabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(doctorbptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(doctorpulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(doctorrecordbtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doctornamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(doctornametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(doctorpphnolabel)
                                .addGap(18, 18, 18)
                                .addComponent(doctorpphnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(doctordatelabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doctordatetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(392, 392, 392)
                                .addComponent(doctordiagnosislabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(doctordiagnosistxt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(doctortemplabel)
                                .addGap(18, 18, 18)
                                .addComponent(doctortemptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(489, 489, 489)
                                .addComponent(Doctorlabelrec))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(jLabel1)
                                .addGap(26, 26, 26)
                                .addComponent(doctorsearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(doctorsearchbtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Doctorlabelrec)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctornamelabel)
                    .addComponent(doctornametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorpphnolabel)
                    .addComponent(doctorpphnotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctordatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctordatelabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctortemplabel)
                            .addComponent(doctortemptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doctordiagnosislabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorbplabel)
                            .addComponent(doctorbptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorpulselabel)
                            .addComponent(doctorpulsetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(doctordiagnosistxt, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doctorrecordbtn)
                        .addGap(2, 2, 2)))
                .addGap(41, 41, 41)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Doctorlabelview)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(doctorsearchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorsearchbtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorsearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorsearchbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorsearchbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Doctorlabelrec;
    private javax.swing.JLabel Doctorlabelview;
    private javax.swing.JLabel doctorbplabel;
    private javax.swing.JTextField doctorbptxt;
    private javax.swing.JLabel doctordatelabel;
    private javax.swing.JTextField doctordatetxt;
    private javax.swing.JLabel doctordiagnosislabel;
    private javax.swing.JTextField doctordiagnosistxt;
    private javax.swing.JLabel doctornamelabel;
    private javax.swing.JTextField doctornametxt;
    private javax.swing.JLabel doctorpphnolabel;
    private javax.swing.JTextField doctorpphnotxt;
    private javax.swing.JLabel doctorpulselabel;
    private javax.swing.JTextField doctorpulsetxt;
    private javax.swing.JButton doctorrecordbtn;
    private javax.swing.JButton doctorsearchbtn;
    private javax.swing.JTextField doctorsearchtxt;
    private javax.swing.JTable doctortable;
    private javax.swing.JLabel doctortemplabel;
    private javax.swing.JTextField doctortemptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
